sudo: required
dist: trusty
addons:
  artifacts:
    paths:
    - results
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
  - bower_components
  - $HOME/.npm
  - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
  - NODE_ENV=testing
  - ARTIFACTS_BUCKET=js-tasks-ru
  - secure: xA6vqbXNWr2C6JiblKqPo6oecVqIl/xPVitFS5GcwKMgabnPVS/r4kwuc6v106R2TkjpXtOk4SQedRlHy6So+F2NNSAREREepZRykszfOs9a90mxXq5nAkw9AFHnCpTnQaisSQM33013o4/P+w/ZYtyNqp8o8Ffgr0c6qasmq+bP9ZyiW+96JYrDQyyBh5KYnnJdY9/4oXOIH11c3FCMz5FB5BMNpU9AzySIf2vTjuvoFXq478+Vm2jH2c69LZ2ARtfSu+MFN4Wsk2K+NGy/g66nY/YI1DPYpxJro8SNYGGRDmZcyewMVF2uVz3AKhyVq6mPkbYJlj0mj/rCO2g/0w8553WQjBem8cn5NS0EXzip3X2ms5LKM64keli9zrPgt3dD+fABVn5nG2MZVNi9m2gn71sX154DAXTUWx8ygMRFdW2q6pJMu+DLvQsz30FraQx80vB4iSRP6XYpV5dfgCUhTon6VP7cqViDwLv6AgxZWR6x20bEe3F5ztXBO3Fn02Rm6n7g0+h8sdtXf1pAVbn35Xgf2EuOHED+JzX6PEO3e06GXoIXy7MG3nZpmhOVAl3lud0hPtslvo7fGbevH8EEaqwTI9XemoLCfvx/FwM5ipMFL/b4j9RBTwVEwUEuYX6Bvj0n00um5NoxhHe2q/0G5BC8H+v4pH48+Ad8+6s=
  - secure: FLjFfSvL0ZvwWet7E6VA9xDka/NiaAkvHkvHs2oswop6qUFankNwhPHM+2escOYh4V+V990uWQqtMnNzwi97lRY57VOmvDXFmshctEfHvLLmF87ID1/XNYNLw4Zrgk29eL37nCFE28mpp/ilwgTXYc1sgz0vNkW+0exJLnBTZKVXvXLgOiyNZ+mGFMFcgZ2b099jyQTZ1fxDxcTfaL40UHh6kYyiPXjBVPiV1zNy/2/ZkYso6hAxjNZBoBREUntxv16PerVfF3cdi26+P3oyKus/i4mVng0KUMDXhLH5VuWvdvjKnM2ggU8cE30Y8ZHZnNBpzzOh+GR738w+9ZpBUB5B9EwObE2xJcFF5Dsh7x6KNcNCbtO8UIkiTmKq8A5j7VqMCimtiOHcBAq+dGbzZPU3I6IAdvp3HPydFNU7/guHi77aVcngwqCsHUsYeuRIz2Xkj/6qoC+lVJJqTTjuF5l/2jor9mzsq9E2nlH2WUA3Ir219oDmtkhhSn5nSls/tgeieZTIvCWCZ1EZefhcgj+pzai4ioR1+AKwbXcFBcKUIdX3a2ZIvXDfIEvqKGTkp5Xu2tJ/eUC5G6LSGYyGi7tRadxEyHntA/E2ZBqPpVT5S5W/YD5+jI4kj8MIDSEvhce+PkLpI45Od2xfYGmBqc8nDou1LTPT17JugOeyxPg=
script:
  - npm test --silent
notifications:
  webhooks: http://testhook.javascript.ru/automation/ci/build
